# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, height_field=200, upload_to='imagez/', width_field=300),
            preserve_default=False,
        ),
    ]
