# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='/blog/imagez', verbose_name='zphoto'),
        ),
    ]
